CREATE TABLE teams (
 team_no  serial PRIMARY KEY,
 lname    text,
 sname    text,
 win      integer,
 loss     integer
);

INSERT INTO teams (lname, sname, win, loss) VALUES
('Baltimore Orioles', 'Baltimore', 0, 0),
('Tampa Bay Rays', 'Tampa Bay', 0, 0),
('Boston Red Sox', 'Boston', 0, 0),
('New York Yankees', 'New York', 0, 0),
('Toronto Blue Jays', 'Toronto', 0, 0),
('Detroit Tigers', 'Detriot', 0, 0),
('Minnesota Twins', 'Minnesota', 0, 0),
('Cleveland Indians', 'Cleveland', 0, 0),
('Chicago White Sox', 'Chicago', 0, 0),
('Kansas City Royals', 'Kansas City', 0, 0),
('Houston Astros', 'Houston', 0, 0),
('Los Angeles Angels', 'Los Angeles', 0, 0),
('Oakland Athletics', 'Oakland', 0, 0),
('Texas Rangers', 'Texas', 0, 0),
('Seattle Mariners', 'Seattle', 0, 0),
('New York Mets', 'New York', 0, 0),
('Washington Nationals', 'Washington', 0, 0),
('Miami Marlins', 'Miami', 0, 0),
('Philadelphia Phillies', 'Philadelphia', 0, 0),
('Atlanta Braves', 'Atlanta', 0, 0),
('Cincinnati Reds', 'Cincinnati', 0, 0),
('Chicago Cubs', 'Chicago', 0, 0),
('Milwaukee Brewers', 'Milwaukee', 0, 0),
('Pittsburgh Pirates', 'Pittsburgh', 0, 0),
('St. Louis Cardinals', 'St. Louis', 0, 0),
('Arizona Diamondbacks', 'Arizona', 0, 0),
('Colorado Rockies', 'Colorado', 0, 0),
('Los Angeles Dodgers', 'Los Angeles', 0, 0),
('San Diego Padres', 'San Diego', 0, 0),
('San Francisco Giants', 'San Francisco', 0, 0);
